apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eks-game-2048
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/HamsaHAhmed7/EKS-Game-Project
    targetRevision: main
    path: infra/kubernetes
  destination:
    server: https://kubernetes.default.svc
    namespace: eks-game-2048
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true