apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eks-game-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: external-nginx
  tls:
  - hosts:
    - game.eks.hamsa-ahmed.co.uk
    secretName: eks-game-tls
  rules:
  - host: game.eks.hamsa-ahmed.co.uk
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: eks-game-service
            port:
              number: 80